version: "3"
services:
  open5e-api:
    image: koprulusector/open5e-api:0.1.1
    environment:
      - OPEN5E_DEBUG=0
      - DJANGO_SECRET=${DJANGO_SECRET}
      - SERVER_NAME=${SERVER_NAME}
      # ports:
      # - "0.0.0.0:8000:8000"
  nginx:
    image: nginx:latest
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - "./nginx/api/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "0.0.0.0:80:80"
